package com.printfeed.model;


import java.io.Serializable;

public class FeedItem implements Serializable {
    /**
     * FeedItem generated by xaled/sqlhelper for database printfeed version 1
     *  https://github.com/xaled/sql-helper.git
     */

    private static final long serialVersionUID = 1L;

    // private variables
    private long id = -1; //Primary key
    private String title;
    private String link;
    private String desc;
    private long srcid;
    private boolean seen;
    private long date;


    // Empty Constructor
    public FeedItem() {

    }



	// Full Constructor
	public FeedItem(String title, String link, String desc, long srcid, boolean seen, long date) {
        this.title = title;
        this.link = link;
        this.desc = desc;
        this.srcid = srcid;
        this.seen = seen;
        this.date = date;
	}


	// getting ID
	public long getId() {
		return this.id;

	}

	// setting Id
	public void setId(long id) {
		this.id = id;

	}

	// getting title
	public String getTitle() {
		return this.title;

	}

	// setting title
	public void setTitle( String title) {
		this.title = title;
	}
	// getting link
	public String getLink() {
		return this.link;

	}

	// setting link
	public void setLink( String link) {
		this.link = link;
	}
	// getting desc
	public String getDesc() {
		return this.desc;

	}

	// setting desc
	public void setDesc( String desc) {
		this.desc = desc;
	}
	// getting srcId
	public Long getSrcId() {
		return this.srcid;

	}

	// setting srcId
	public void setSrcId( Long srcid) {
		this.srcid = srcid;
	}
	// getting seen
	public Boolean getSeen() {
		return this.seen;

	}

	// setting seen
	public void setSeen( Boolean seen) {
		this.seen = seen;
	}
	// getting date
	public Long getDate() {
		return this.date;

	}

	// setting date
	public void setDate( Long date) {
		this.date = date;
	}



	@Override
	public String toString() {
		return "FeedItem [id=" + id + ", title=" + title + ", link=" + link
				+ ", desc=" + desc + ", srcid=" + srcid + ", seen=" + seen
				+ ", date=" + date + "]";
	}
	
	

}
